name: layout_whatsapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.0
  get: 4.3.8
  image_picker: ^0.8.4+4
  flutter_chat_ui: ^1.5.1
  
  flutter: 
    sdk: flutter
  

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

